sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- branch_exists=$(git ls-remote --heads https://github.com/NetAppDocs/test.git gh-pages)
- if [[ ! -z "$branch_exists" ]]; then
  echo "Adding GH Pages Branch";
  git submodule add -b gh-pages https://github.com/NetAppDocs/test _nl;
  ls -al .;
  ls -al _nl;
  fi
- gem update --system && gem install bundler && gem update bundler
- echo "Pull Request? $TRAVIS_PULL_REQUEST | Branch [$TRAVIS_PULL_REQUEST_BRANCH]";
- if [[ "$TRAVIS_BRANCH" =~ master && $TRAVIS_PULL_REQUEST -eq 0 && -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then
  echo "Site Translation Enabled";
  mv -f dependencies/jekyll/_nl/mantra.rb dependencies/jekyll/_plugins/mantra.rb;
  mv -f dependencies/jekyll/_nl/na-l10n.rb dependencies/jekyll/_plugins/na-i18n.rb;
  mv -f dependencies/jekyll/_config.stage.yml dependencies/jekyll/_config.yml;
  else
  echo "Skipping Translation";
  unset MT_USER;
  unset MT_PSWD;
  unset MT_CLIENT;
  unset MT_SECRET;
  fi
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle exec rake deploy --trace
