sudo: false
dist: xenial
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- echo "Pull Request? $TRAVIS_PULL_REQUEST | Branch [$TRAVIS_PULL_REQUEST_BRANCH]";
- if [[ "$TRAVIS_BRANCH" =~ master && $TRAVIS_PULL_REQUEST -eq 0 && -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then
  echo "Deploying content";
  mv -f dependencies/jekyll/_config.occm.yml dependencies/jekyll/_config.yml;
  export DEPLOY_BRANCH=gh-pages;
  else
  echo "Skipping Deployment";
  fi
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
- echo "Determining Sites"
- ls -al .
- pwd
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  local_dir: $TRAVIS_BUILD_DIR
  target_branch: $DEPLOY_BRANCH
  verbose: true
  on:
    branch: master
