---
settings:
  name: Cloud Manager Automation
  platform: ''
  noindex: true
  internal:
    pdf_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: false
    api_enabled: true
sidebar:
  entries:
    - title: Cloud Manager API docs
      url: /index.html
    - section: platform
    - section: cat-api-ss
    - section: cat-api-ps
    - section: cat-wf-ss
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
