---
settings:
  name: ''
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Demo docs
      url: /index.html
    - title: Installation
      url: /task_install.html
    - title: Troubleshooting
      url: /task_troubleshooting.html
